name: pull_request_created
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md' ### Ignore running when .md files change
      - '**.yaml' ### Ignore running when .md files change
      - '**.json' ### Ignore running when .md files change
      - '.github/*' ### Ignore running when files under path: .github/* changed.

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pr-created:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-created.yaml@main
    with:
      GO_VERSION: "1.25"
    secrets: inherit
